// packages/react-host/src/App.jsx
import React, { useRef, useEffect } from "react";
import ReactDOM from "react-dom";

import placeFooter from "remote/placeFooter";
import "./index.scss";

const App = () => {
  const footerRef = useRef(null);

  useEffect(() => {
    placeFooter(footerRef.current);
  }, []);

  return (
    <div className="mt-10 text-3xl mx-auto max-w-6xl">
      <div>Name: react-host</div>
      <div>Framework: react</div>
      <div>Language: JavaScript</div>
      <div>CSS: Tailwind</div>
      <div ref={footerRef} />
    </div>
  );
};

ReactDOM.render(<App />, document.getElementById("app"));

// packages/remote/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <Header />
    <div>Name: remote</div>
    <div>Framework: vue3</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
  </div>
</template>

<script>
import Header from "./Header.vue";
export default {
 components: {
  Header
 }
}
</script>
